// src/views/EmployeeList.vue
<template>
  <div>
    <h2 class="text-2xl font-bold mb-4">従業員一覧</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
      <div v-for="department in departments" :key="department.id" class="space-y-2">
        <h3 class="font-semibold text-lg text-blue-800">{{ department.name }}</h3>
        <div v-for="employee in employeesByDepartment(department.id)" :key="employee.id"
             class="bg-white p-3 rounded-md shadow-sm cursor-pointer hover:shadow-md transition-shadow"
             @click="selectEmployee(employee)">
          <div class="flex justify-between items-center">
            <span class="font-medium">{{ employee.name }}</span>
            <span :class="getStatusColor(employee.status)">{{ employee.status }}</span>
          </div>
        </div>
      </div>
    </div>
    <EmployeeModal v-if="selectedEmployee" :employee="selectedEmployee" @close="selectedEmployee = null" />
  </div>
</template>

<script>
import { ref, onMounted, computed } from 'vue'
import axios from 'axios'
import EmployeeModal from '../components/EmployeeModal.vue'

export default {
  name: 'EmployeeList',
  components: {
    EmployeeModal
  },
  setup() {
    const departments = ref([])
    const employees = ref([])
    const selectedEmployee = ref(null)

    const fetchData = async () => {
      try {
        const [deptResponse, empResponse] = await Promise.all([
          axios.get('http://localhost:8000/api/departments/'),
          axios.get('http://localhost:8000/api/employees/')
        ])
        departments.value = deptResponse.data
        employees.value = empResponse.data
      } catch (error) {
        console.error('Error fetching data:', error)
      }
    }

    onMounted(fetchData)

    const employeesByDepartment = (departmentId) => {
      return employees.value.filter(emp => emp.department === departmentId)
    }

    const getStatusColor = (status) => {
      switch (status) {
        case '出勤': return 'text-green-600'
        case '退勤': return 'text-red-600'
        case '外出': return 'text-yellow-600'
        default: return 'text-gray-600'
      }
    }

    const selectEmployee = (employee) => {
      selectedEmployee.value = employee
    }

    return {
      departments,
      employees,
      selectedEmployee,
      employeesByDepartment,
      getStatusColor,
      selectEmployee
    }
  }
}
</script>

// src/components/EmployeeList.tsx
import React, { useState } from 'react';
import { Employee, Department } from '../types';
import EmployeeModal from './EmployeeModal';

interface EmployeeListProps {
  employees: Employee[];
  departments: Department[];
}

const EmployeeList: React.FC<EmployeeListProps> = ({ employees, departments }) => {
  const [selectedEmployee, setSelectedEmployee] = useState<Employee | null>(null);

  const groupedEmployees = employees.reduce((acc, employee) => {
    const dept = departments.find(d => d.id === employee.departmentId);
    if (dept) {
      if (!acc[dept.name]) {
        acc[dept.name] = [];
      }
      acc[dept.name].push(employee);
    }
    return acc;
  }, {} as Record<string, Employee[]>);

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
      {Object.entries(groupedEmployees).map(([deptName, deptEmployees]) => (
        <div key={deptName} className="space-y-2">
          <h3 className="font-semibold text-lg text-blue-800">{deptName}</h3>
          {deptEmployees.map((employee) => (
            <div
              key={employee.id}
              onClick={() => setSelectedEmployee(employee)}
              className="bg-white p-3 rounded-md shadow-sm cursor-pointer hover:shadow-md transition-shadow"
            >
              <div className="flex justify-between items-center">
                <span className="font-medium">{employee.name}</span>
                <span className={`text-sm ${getStatusColor(employee.status)}`}>
                  {employee.status}
                </span>
              </div>
            </div>
          ))}
        </div>
      ))}
      {selectedEmployee && (
        <EmployeeModal
          employee={selectedEmployee}
          onClose={() => setSelectedEmployee(null)}
        />
      )}
    </div>
  );
};

function getStatusColor(status: string): string {
  switch (status) {
    case '出勤':
      return 'text-green-600';
    case '退勤':
      return 'text-red-600';
    case '外出':
      return 'text-yellow-600';
    default:
      return 'text-gray-600';
  }
}

export default EmployeeList;
